source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios ,'8.0'
target 'swiftProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	  pod 'MJRefresh', :git => 'https://gitee.com/wyc520/MJRefresh.git',:tag => '3.2.0'
    pod 'SDWebImage', :git => 'https://gitee.com/wyc520/SDWebImage.git', :tag => '5.2.2'
    pod 'SnapKit'
    pod 'RxSwift'
    pod 'HandyJSON' , :git => 'https://gitee.com/wyc520/HandyJSON.git'
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'FMDB'
    pod 'LLCycleScrollView'
    pod 'RxDataSources'
    pod 'RxAlamofire'
    pod 'ObjectMapper'

end
