platform :ios ,'8.0'
target 'swiftProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
#    pod 'Alamofire'
	pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'SnapKit'
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'HandyJSON', '~> 4.2.0'
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'FMDB'
    pod 'LLCycleScrollView'
    pod 'RxDataSources', '~> 3.0'
    pod 'RxAlamofire'
    pod 'ObjectMapper', '~> 3.4'

end
