target 'swiftProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire'
	pod 'Kingfisher'
	pod 'MJRefresh'
	pod 'MJExtension'
	pod 'SnapKit'
    pod 'SDWebImage'

end
